//Generated by GetAllHeaderLinks - header-links
import {
  Home,
  //Generated by GetAllItemIcons
  List,
  Clock,
  Tag,
  File,
  CheckSquare,
} from "lucide-react";

export const links = [
  { id: 0, name: "Home", href: "/", icon: Home },
  //Generated by GetModelHeaderLinkItem - header link item
  {
    id: "task-categories",
    name: "Task Categories",
    href: "/task-categories",
    icon: List,
  },
  //Generated by GetModelHeaderLinkItem - header link item
  {
    id: "task-intervals",
    name: "Task Intervals",
    href: "/task-intervals",
    icon: Clock,
  },
  //Generated by GetModelHeaderLinkItem - header link item
  { id: "tags", name: "Tags", href: "/tags", icon: Tag },
  //Generated by GetModelHeaderLinkItem - header link item
  {
    id: "task-templates",
    name: "Task Templates",
    href: "/task-templates",
    icon: File,
  },
  //Generated by GetModelHeaderLinkItem - header link item
  { id: "tasks", name: "Tasks", href: "/tasks", icon: CheckSquare },
];
