//Generated by GetAllHeaderLinks - header-links
export const links = [
  { id: 1, name: "Home", href: "/" },
 //Generated by GetModelHeaderLinkItem - header link item
{ id: 1, name: "Task Categories", href: "/task-categories" },
//Generated by GetModelHeaderLinkItem - header link item
{ id: 2, name: "Task Intervals", href: "/task-intervals" }
];
