//Generated by WriteToUsemodelquery_ts - useModelQuery.ts
import {
  GetTaskTemplatesResponse,
  TaskTemplateDeletePayload,
  TaskTemplateFormUpdatePayload,
  TaskTemplateModel,
  TaskTemplateSearchParams,
  TaskTemplateUpdatePayload,
} from "@/interfaces/TaskTemplateInterfaces";
import axiosClient from "@/utils/api";
import {
  DEFAULT_FILTERS,
  MODEL_PATH,
  PRIMARY_KEY,
} from "@/utils/constants/TaskTemplateConstants";
import { getAxiosParams } from "@/utils/utilities";
import {
  QueryMeta,
  UseQueryResult,
  useInfiniteQuery,
  useMutation,
  useQuery,
} from "@tanstack/react-query";

type IndexAndID = {
  index: number;
  id: number | string;
};

type Response = {
  id?: number | string;
  slug?: string;
  //Generated by GetAllRelatedIndexAndID
  SubTaskTemplates: IndexAndID[];
  Tasks: IndexAndID[];
};

export const updateTaskTemplates = async (
  payload: TaskTemplateUpdatePayload
) => {
  const { data } = (await axiosClient({
    url: `${MODEL_PATH}/multi`,
    method: "post",
    data: payload,
  })) as { data: { recordsCreated: number } };

  return data;
};

export const deleteTaskTemplates = async (
  payload: TaskTemplateDeletePayload
) => {
  const { data } = (await axiosClient({
    url: `${MODEL_PATH}`,
    method: "delete",
    data: payload,
  })) as { data: { recordsDeleted: number } };

  return data;
};

const updateTaskTemplate = async (
  payload: TaskTemplateFormUpdatePayload,
  id: string | number
) => {
  const { data } = await axiosClient({
    url: MODEL_PATH + "/" + id,
    method: "put",
    data: payload,
  });

  return data as Response;
};

const addTaskTemplate = async (payload: TaskTemplateFormUpdatePayload) => {
  const { data } = await axiosClient({
    url: MODEL_PATH,
    method: "post",
    data: payload,
  });

  return data as Response;
};

export const getTaskTemplate = async ({
  queryKey,
}: {
  queryKey: [string, string];
}) => {
  const { data } = await axiosClient.get<TaskTemplateModel>(
    `${MODEL_PATH}/${queryKey[1]}`
  );
  return data;
};

const addOrUpdateTaskTemplate = (payload: TaskTemplateFormUpdatePayload) => {
  if (payload[PRIMARY_KEY]) {
    return updateTaskTemplate(payload, payload[PRIMARY_KEY]);
  } else {
    return addTaskTemplate(payload);
  }
};

export const useTaskTemplateQuery = (
  slug: string,
  options?: Parameters<typeof useQuery>[2]
) => {
  const taskTemplateMutation = useMutation(addOrUpdateTaskTemplate);

  const taskTemplateQuery = useQuery(
    ["taskTemplate", slug],
    getTaskTemplate,
    //@ts-ignore
    options
  ) as UseQueryResult<TaskTemplateModel, any>;

  return { taskTemplateMutation, taskTemplateQuery };
};

//Generated by GetCodeOriginallyFromModelTable - GetCodeOriginallyFromModelTable
interface GetTaskTemplatesProps {
  pageParam?: string;
  queryKey: [string, Partial<TaskTemplateSearchParams>];
  meta: QueryMeta | undefined;
}
const getTaskTemplates = async ({
  pageParam = "",
  queryKey,
  meta,
}: GetTaskTemplatesProps) => {
  const [
    _,
    {
      //Generated by GetAllQueryKeyValueOfGetPluralizedModelName
      q = "", //Generated by GetQueryKeyValueOfGetPluralizedModelName - GetQueryKeyValueOfGetPluralizedModelName
      taskCategory = "", //Generated by GetQueryKeyValueOfGetPluralizedModelName - GetQueryKeyValueOfGetPluralizedModelName
      taskInterval = "", //Generated by GetQueryKeyValueOfGetPluralizedModelName - GetQueryKeyValueOfGetPluralizedModelName
      limit = "",
      sort = "",
    },
  ] = queryKey;

  const { fetchCount } = meta!;

  const axiosParams = getAxiosParams(
    {
      //Generated by GetAllFilterQueryNameBySeqModel
      q,
      taskCategory,
      taskInterval,
    },
    DEFAULT_FILTERS,
    {
      cursor: pageParam,
      limit,
      sort,
      //@ts-ignore
      fetchCount: fetchCount.toString(),
    }
  ) as Partial<TaskTemplateSearchParams>;

  const { data } = await axiosClient.get<GetTaskTemplatesResponse>(MODEL_PATH, {
    params: axiosParams,
  });

  return data;
};

interface UseTaskTemplatesQueryProps
  extends Partial<TaskTemplateSearchParams> {}

export const useTaskTemplatesQuery = ({
  //Generated by GetAllFilterQueryNameBySeqModel
  q,
  taskCategory,
  taskInterval,
  limit,
  sort,
  fetchCount,
}: UseTaskTemplatesQueryProps) => {
  const _ = useInfiniteQuery(
    [
      "taskTemplates",
      {
        //Generated by GetAllFilterQueryNameBySeqModel
        q,
        taskCategory,
        taskInterval,
        limit,
        sort,
      },
    ],
    getTaskTemplates,
    {
      keepPreviousData: true,
      getNextPageParam: (lastPage) => lastPage.cursor ?? undefined,
      meta: {
        fetchCount,
      },
    }
  );
  return _;
};
