//Generated by WriteToUsemodelstore_ts - useModelStore.ts
import { TaskTemplateModel } from "@/interfaces/TaskTemplateInterfaces";
import { Slice, modelSlice } from "@/lib/zustand-slice";
import { TaskTemplateConfig } from "@/utils/config/TaskTemplateConfig";
import { create } from "zustand";

const useTaskTemplateStore = create<Slice<TaskTemplateModel>>((set) =>
  modelSlice<TaskTemplateModel>(set, TaskTemplateConfig.sortString)
);

export { useTaskTemplateStore };
