//Generated by WriteToModelsPage - Model Page Sidebar
import React from "react";
import TaskFilterForm from "@/components/tasks/TaskFilterForm";
import TaskTable from "@/components/tasks/TaskTable";
import PageSession from "@/components/PageSession";

export const metadata = {
  title: "Tasks",
};

const Tasks: React.FC = () => {
  return (
    <>
      <div className="flex flex-col flex-1 w-full px-4 mx-auto text-sm lg:px-0 main-height-less-footer">
        <div className="flex flex-col flex-1 w-full gap-4 p-4 mx-auto border rounded-sm border-border">
          <h1 className="text-2xl font-bold">Tasks</h1>
          <div className="flex">
            <TaskFilterForm />
          </div>
          <div className="flex flex-col flex-1 ">
            <TaskTable />
          </div>
        </div>
      </div>
      <PageSession />
    </>
  );
};

export default Tasks;
