//Generated by WriteToModelsPage - Model Page Sidebar
import React from "react";
import PageSession from "@/components/PageSession";
import { TaskConfig } from "@/utils/config/TaskConfig";
import TaskStateHolder from "@/components/tasks/TaskStateHolder";

const config = TaskConfig;

export const metadata = {
  title: config.pluralizedVerboseModelName,
};

const Tasks: React.FC = () => {
  return (
    <>
      <div className="flex flex-col flex-1 w-full mx-auto text-sm 2xl:px-0 main-height-less-footer">
        <div className="flex flex-col flex-1 w-full gap-4 pl-4 mx-auto rounded-sm">
          <h1 className="text-2xl font-bold">
            {config.pluralizedVerboseModelName}
          </h1>
          <TaskStateHolder modelConfig={config} />
        </div>
      </div>
      <PageSession />
    </>
  );
};

export default Tasks;
