//Generated by WriteToModelconstants_ts - ModelConstants.ts
import { SubTaskFormikFilter } from "@/interfaces/SubTaskInterfaces";
import { convertDateToYYYYMMDD } from "@/utils/utilities";

export const MODEL_NAME = "SubTask";
export const TABLE_NAME = "taskmanager_subtask";
export const PLURALIZED_MODEL_NAME = "SubTasks";
export const VERBOSE_MODEL_NAME = "Sub Task";
export const PLURALIZED_VERBOSE_MODEL_NAME = "Sub Tasks";
export const DEFAULT_SORT_BY = "priority";
export const DEFAULT_FILTERS: Partial<SubTaskFormikFilter> = {
  //Generated by GetAllModelFilterDefaultBySeqModel
};
export const FIRST_FIELD_IN_FORM = "description"; //Generated by GetFirstFieldInForm
export const LAST_FIELD_IN_FORM = "taskID"; //Generated by GetLastFieldInForm
export const DEFAULT_FORM_VALUE = {
  //Generated by GetAllFormDefaultValueBySeqModel
  id: "", //Generated by GetFormDefaultValue
  description: "", //Generated by GetFormDefaultValue
  priority: "0.00", //Generated by GetFormDefaultValue
  finishDateTime: null, //Generated by GetFormDefaultValue
  taskID: "", //Generated by GetFormDefaultValue,
  touched: false,
};
export const PRIMARY_KEY = "id";
export const UNIQUE_FIELDS = [
  //Generated by GetAllUniqueFieldsBySeqModel
];
export const REQUIRED_FIELDS = {
  //Generated by GetAllRequiredFieldsBySeqModel
  description: "Description", //Generated by GetRequiredField - Get Required Field
  priority: "Priority", //Generated by GetRequiredField - Get Required Field
  taskID: "Task ID", //Generated by GetRequiredField - Get Required Field
};

//Generated by GetControlOptionsBySeqModel
export const CONTROL_OPTIONS = {};

//Generated by GetCOLUMNSObject
export const COLUMNS = {
  id: { type: "number", db_name: "id" }, //Generated by GetConstantFieldDictionary - Constant Field Dictionary
  description: { type: "string", db_name: "description" }, //Generated by GetConstantFieldDictionary - Constant Field Dictionary
  priority: { type: "number", db_name: "priority" }, //Generated by GetConstantFieldDictionary - Constant Field Dictionary
  finishDateTime: { type: "string", db_name: "finish_date_time" }, //Generated by GetConstantFieldDictionary - Constant Field Dictionary
  taskID: { type: "number", db_name: "task_id" }, //Generated by GetConstantFieldDictionary - Constant Field Dictionary
};
