//Generated by WriteToModelconstants_ts - ModelConstants.ts
import { TaskTagFormikFilter } from "@/interfaces/TaskTagInterfaces";

export const MODEL_NAME = "TaskTag";
export const TABLE_NAME = "taskmanager_task_tags";
export const PLURALIZED_MODEL_NAME = "TaskTags";
export const VERBOSE_MODEL_NAME = "Task Tag";
export const PLURALIZED_VERBOSE_MODEL_NAME = "Task Tags";
export const DEFAULT_SORT_BY = "id";
export const DEFAULT_FILTERS: Partial<TaskTagFormikFilter> = {
  //Generated by GetAllModelFilterDefaultBySeqModel
};
export const FIRST_FIELD_IN_FORM = "taskID"; //Generated by GetFirstFieldInForm
export const LAST_FIELD_IN_FORM = "tagID"; //Generated by GetLastFieldInForm
export const DEFAULT_FORM_VALUE = {
  //Generated by GetAllFormDefaultValueBySeqModel
  id: "", //Generated by GetFormDefaultValue
  taskID: "", //Generated by GetFormDefaultValue
  tagID: "", //Generated by GetFormDefaultValue,
  touched: false,
};
export const PRIMARY_KEY = "id";
export const UNIQUE_FIELDS = [
  //Generated by GetAllUniqueFieldsBySeqModel
];
export const REQUIRED_FIELDS = {
  //Generated by GetAllRequiredFieldsBySeqModel
  taskID: "Task ID", //Generated by GetRequiredField - Get Required Field
  tagID: "Tag ID", //Generated by GetRequiredField - Get Required Field
};

//Generated by GetControlOptionsBySeqModel
export const CONTROL_OPTIONS = {};

//Generated by GetCOLUMNSObject
export const COLUMNS = {
  id: { type: "number", db_name: "id" }, //Generated by GetConstantFieldDictionary - Constant Field Dictionary
  taskID: { type: "number", db_name: "task_id" }, //Generated by GetConstantFieldDictionary - Constant Field Dictionary
  tagID: { type: "number", db_name: "tag_id" }, //Generated by GetConstantFieldDictionary - Constant Field Dictionary
};
