//Generated by WriteToModelfilterform_tsx - ModelFilterForm.tsx
"use client";
import { useTagStore } from "@/hooks/tags/useTagStore";
import { TagFormikFilter, TagSearchParams } from "@/interfaces/TagInterfaces";
import { DEFAULT_LIMIT } from "@/utils/constants";
import { getFilterValueFromURL, getParamsObject } from "@/utils/utilities";
import { encodeParams } from "@/utils/utils";
import { Form, Formik, FormikHelpers, FormikProps } from "formik";
import React, { MouseEventHandler } from "react";
import {
  DEFAULT_FILTERS,
  CONTROL_OPTIONS,
} from "@/utils/constants/TagConstants";
import LimitSelector from "@/components/form/LimitSelector";
import { useURL } from "@/hooks/useURL";
import FormikControl from "@/components/form/FormikControl";
import { Button } from "@/components/ui/Button";
import { isEqual } from "lodash";
import { useTagPageParams } from "@/hooks/tags/useTagPageParams";
//Generated by ImportAllUseModelListHookBySeqModel

const TagFilterForm: React.FC = () => {
  const { query, router, pathname, params } = useTagPageParams();
  const { limit } = params;

  const defaultFilters = DEFAULT_FILTERS;
  const initialValues: TagFormikFilter = getFilterValueFromURL(
    query,
    defaultFilters
  );

  //Tanstack queries
  //Generated by GetRequiredQueryFromTanstackBySeqModel

  //Zustand stores
  const [setPage, setLastFetchedPage, setFetchCount, resetRowSelection] =
    useTagStore((state) => [
      state.setPage,
      state.setLastFetchedPage,
      state.setFetchCount,
      state.resetRowSelection,
    ]);

  const handleFormikSubmit = (
    values: Partial<TagFormikFilter>,
    formik: FormikHelpers<TagFormikFilter>
  ) => {
    const params = {
      ...query,
      ...(getParamsObject(values, defaultFilters) as Partial<TagSearchParams>),
    };

    const newURL = `${pathname}?${encodeParams(params)}`;
    router.push(newURL);
    setFetchCount(true);
    setPage(1);
    setLastFetchedPage(1);
    resetRowSelection();
  };

  const handleLimitChange = (value: string) => {
    const params = { ...query, limit: value };
    const newURL = `${pathname}?${encodeParams(params)}`;
    router.push(newURL);
    resetRowSelection();
  };

  const renderFormik = (formik: FormikProps<TagFormikFilter>) => {
    const filtered = isEqual(defaultFilters, formik.values);

    const handleSubmitClick: MouseEventHandler = (e) => {
      e.preventDefault();
      formik.submitForm();
    };

    const handleClearClick: MouseEventHandler = (e) => {
      e.preventDefault();
      formik.setValues(defaultFilters as TagFormikFilter);
      formik.submitForm();
    };

    return (
      <Form
        className="flex gap-2 w-[750px]"
        autoComplete="off"
      >
        {/* Generated by GetFormikFilterQControl - GetFormikFilterQControl */}
        <FormikControl
          name="q"
          placeholder="Filter Tags..."
          type="Text"
          containerClassNames={["w-[250px]"]}
        />
        {/* Generated by GetAllFormikFilterControlBySeqModel */}
        <Button
          type="button"
          onClick={handleSubmitClick}
          size={"sm"}
          variant={"secondary"}
        >
          Search
        </Button>
        <Button
          type="button"
          size={"sm"}
          variant={"ghost"}
          disabled={filtered}
          onClick={handleClearClick}
        >
          Clear
        </Button>
      </Form>
    );
  };

  return (
    <div className="flex justify-between w-full">
      <Formik
        initialValues={initialValues}
        onSubmit={handleFormikSubmit}
      >
        {renderFormik}
      </Formik>
      <LimitSelector
        handleLimitChange={handleLimitChange}
        value={limit}
      />
    </div>
  );
};

export default TagFilterForm;
