//Generated by WriteToModelcolumns_tsx - ModelColumns.tsx
"use client";
import { ColumnDef, createColumnHelper } from "@tanstack/react-table";
import { Checkbox } from "@/components/ui/Checkbox";
import { TaskTemplateModel } from "@/interfaces/TaskTemplateInterfaces";
import { DeleteRowColumn } from "@/components/ui/DataTable/DeleteRowColumn";

import TaskTemplateSingleColumn from "@/components/task-templates/TaskTemplateSingleColumn";
import { TaskTemplateConfig } from "@/utils/config/TaskTemplateConfig";
import { createTableColumns } from "@/lib/table-utils";
import { ModelRowActions } from "@/components/ModelRowActions";

const taskTemplateColumnHelper = createColumnHelper<TaskTemplateModel>();
const config = TaskTemplateConfig;

export const TaskTemplateColumns: ColumnDef<TaskTemplateModel, unknown>[] = [
  {
    id: "select",
    header: ({ table }) => {
      const toggleSelectAllRow = table.options.meta?.toggleSelectAllRow;
      return (
        <div className="flex justify-center w-full">
          <Checkbox
            tabIndex={-1}
            checked={table.getIsAllPageRowsSelected()}
            onCheckedChange={() => {
              toggleSelectAllRow && toggleSelectAllRow();
            }}
            aria-label="Select all"
          />
        </div>
      );
    },
    cell: ({ row, table }) => {
      const toggleRow = table.options.meta?.toggleRow;
      return (
        <div className="flex justify-center">
          <Checkbox
            tabIndex={-1}
            checked={row.getIsSelected()}
            onCheckedChange={() => {
              toggleRow && toggleRow(row.index);
            }}
            aria-label="Select row"
          />
        </div>
      );
    },
  },
  {
    id: "singleColumn",
    header: () => (
      <div className="flex justify-center w-full">
        {config.pluralizedVerboseModelName}
      </div>
    ),
    cell: (cell) => <TaskTemplateSingleColumn cell={cell} />,
  },
  ...createTableColumns<TaskTemplateModel>(config, taskTemplateColumnHelper),
  {
    id: "actions",
    //cell component generated by GetActionCell
    cell: (cell) =>
      config.isRowAction ? (
        <ModelRowActions
          cell={cell}
          modelConfig={config}
        />
      ) : (
        <DeleteRowColumn {...cell} />
      ),
  },
];
