//Generated by WriteToModelstateholder_tsx - ModelStateHolder.tsx
"use client";
import TaskTemplateFilterForm from "@/components/task-templates/TaskTemplateFilterForm";
import TaskTemplateTable from "@/components/task-templates/TaskTemplateTable";
import { useTableProps } from "@/hooks/useTableProps";
import { ModelConfig } from "@/interfaces/ModelConfig";
import TaskTemplateModel from "@/models/TaskTemplateModel";
import React from "react";

const TaskTemplateStateHolder = ({
  modelConfig,
}: {
  modelConfig: ModelConfig;
}) => {
  const tableStates = useTableProps<TaskTemplateModel>(modelConfig);
  return (
    <>
      <div className="flex">
        <TaskTemplateFilterForm tableStates={tableStates} />
      </div>
      <div className="flex flex-col flex-1 ">
        <TaskTemplateTable tableStates={tableStates} />
      </div>
    </>
  );
};

export default TaskTemplateStateHolder;
