//Generated by WriteToModelrowactions_tsx - ModelRowActions.tsx
"use client";

import { CellContext } from "@tanstack/react-table";

import { Button } from "@/components/ui/Button";
import {
  DropdownMenu,
  DropdownMenuContent,
  DropdownMenuItem,
  DropdownMenuTrigger,
} from "@/components/ui/DropdownMenu";
import { MoreHorizontal } from "lucide-react";
import {
  TaskTemplateFormikShape,
  TaskTemplateModel,
} from "@/interfaces/TaskTemplateInterfaces";
import Link from "next/link";
import { useTaskTemplateStore } from "@/hooks/task-templates/useTaskTemplateStore";
import { useState } from "react";

interface TaskTemplateRowActionsProps<TData, TValue> {
  cell: CellContext<TData, TValue>;
}

export function TaskTemplateRowActions<TData, TValue>({
  cell,
}: TaskTemplateRowActionsProps<TData, TValue>) {
  //local state
  const [open, setOpen] = useState(false);

  //Variables from cell
  const rowData = cell.row.original as TaskTemplateFormikShape;

  //@ts-ignore
  const { currentData }: { currentData: TaskTemplateModel[] } =
    useTaskTemplateStore((state) => ({
      currentData: state.currentData,
    }));

  const id = rowData.id;
  const slug = currentData.find((item) => item.id === id)?.id;

  const index = cell.row.index;

  //Varuables from table meta
  //@ts-ignore
  const deleteRow = cell.table.options.meta.deleteRow;

  //Transformations
  const isHidden = !rowData.id;

  return (
    !isHidden && (
      <DropdownMenu open={open}>
        <DropdownMenuTrigger asChild>
          <Button
            variant="ghost"
            className="flex w-8 h-8 p-0"
            type="button"
            onClick={() => {
              setOpen(true);
            }}
          >
            <MoreHorizontal className="w-4 h-4 text-muted-foreground" />
            <span className="sr-only">Open menu</span>
          </Button>
        </DropdownMenuTrigger>

        <DropdownMenuContent
          align="end"
          className="w-[160px]"
          onPointerDownOutside={() => {
            setOpen(false);
          }}
        >
          <DropdownMenuItem
            onSelect={() => {
              setOpen(false);
              deleteRow && deleteRow(index);
            }}
          >
            Delete
          </DropdownMenuItem>
          <Link href={`/task-templates/${slug}`}>
            <DropdownMenuItem>Edit/View Task Template Details</DropdownMenuItem>
          </Link>
        </DropdownMenuContent>
      </DropdownMenu>
    )
  );
}
