//Generated by WriteToModeltable_tsx - ModelTable.tsx for Table 9/18
"use client";
import React, { useEffect } from "react";
import { useTaskStore } from "@/hooks/tasks/useTaskStore";
import TaskDataTable from "@/components/tasks/TaskDataTable";
import { useTaskPageParams } from "@/hooks/tasks/useTaskPageParams";
import { useTasksQuery } from "@/hooks/tasks/useTaskQuery";
import { GetTasksResponse, TaskModel } from "@/interfaces/TaskInterfaces";
import { VARIABLE_PLURAL_NAME } from "@/utils/constants/TagConstants";
import { useQueryClient, InfiniteData } from "@tanstack/react-query";
import _ from "lodash";

const TaskTable: React.FC = () => {
  const { params } = useTaskPageParams();
  const queryClient = useQueryClient();

  //Store Variables
  const page = useTaskStore((state) => state.page);
  const setRecordCount = useTaskStore((state) => state.setRecordCount);
  const fetchCount = useTaskStore((state) => state.fetchCount);
  const setFetchCount = useTaskStore((state) => state.setFetchCount);
  const previousData = useTaskStore((state) => state.currentData);
  const setCurrentData = useTaskStore((state) => state.setCurrentData);
  const setQueryResponse = useTaskStore((state) => state.setQueryResponse);
  const setRefetchQuery = useTaskStore((state) => state.setRefetchQuery);

  const queryParams = params;

  const taskQuery = () =>
    useTasksQuery({
      ...queryParams,
      fetchCount: fetchCount.toString(),
    });

  const { data, refetch, isFetching, isLoading } = taskQuery();

  const currentPageData: GetTasksResponse | null = data
    ? data.pages[page - (isFetching ? 2 : 1)]
    : null;
  const currentData: TaskModel[] =
    currentPageData === null ? previousData : currentPageData?.rows || [];

  //Client functions
  const refetchQuery = (idx: number) => {
    queryClient.setQueryData(
      [VARIABLE_PLURAL_NAME, { ...queryParams }],
      (data: InfiniteData<GetTasksResponse> | undefined) => {
        return data
          ? {
              pages: data.pages.slice(0, idx + 1),
              pageParams: data.pageParams.slice(0, idx + 1),
            }
          : undefined;
      }
    );
    refetch({
      refetchPage(lastPage, index) {
        return index === idx;
      },
    });
  };

  useEffect(() => {
    setQueryResponse(taskQuery);
    if (currentPageData?.count !== undefined) {
      setRecordCount(currentPageData?.count || 0);
    }
    setFetchCount(!fetchCount);
    setCurrentData(currentData);
    setRefetchQuery(refetchQuery);
  }, [currentPageData?.count, data, page]);

  return <TaskDataTable taskQuery={taskQuery} />;
};

export default TaskTable;
