//Generated by WriteToModellibs_ts - ModelLibs.ts
import { SubTaskTemplateFormikShape } from "@/interfaces/SubTaskTemplateInterfaces";
import { SubTaskTemplate } from "@/models/SubTaskTemplateModel";
import { Op } from "sequelize";
import { Transaction } from "sequelize";

//Reusable functions
export const createSubTaskTemplate = async (
  subTaskTemplate: Omit<SubTaskTemplateFormikShape, "touched" | "index" | "id">,
  t: Transaction
) => {
  return await SubTaskTemplate.create(
    {
      //Generated by GetAllFieldsToUpdateBySeqModel
      description: subTaskTemplate.description!,
      priority: subTaskTemplate.priority!,
      taskTemplateID: parseInt(subTaskTemplate.taskTemplateID as string),
    },
    { transaction: t }
  );
};

export const updateSubTaskTemplate = async (
  subTaskTemplate: Omit<SubTaskTemplateFormikShape, "touched" | "index">,
  primaryKey: keyof Omit<SubTaskTemplateFormikShape, "touched" | "index">,
  t: Transaction,
  primaryKeyValue?: string | number
) => {
  await SubTaskTemplate.update(
    {
      //Generated by GetAllFieldsToUpdateBySeqModel
      description: subTaskTemplate.description!,
      priority: subTaskTemplate.priority!,
      taskTemplateID: parseInt(subTaskTemplate.taskTemplateID as string),
    },
    {
      where: { [primaryKey]: primaryKeyValue || subTaskTemplate[primaryKey] },
      transaction: t,
      individualHooks: true,
    }
  );
};

export const deleteSubTaskTemplates = async (
  primaryKey: keyof Omit<SubTaskTemplateFormikShape, "touched">,
  deletedIds: string[] | number[],
  t: Transaction
) => {
  await SubTaskTemplate.destroy({
    where: { [primaryKey]: { [Op.in]: deletedIds } },
    transaction: t,
  });
};
