//Generated by WriteToModellibs_ts - ModelLibs.ts
import { SubTaskFormikShape } from "@/interfaces/SubTaskInterfaces";
import { SubTask } from "@/models/SubTaskModel";
import { PRIMARY_KEY } from "@/utils/constants/TaskIntervalConstants";
import { Op } from "sequelize";
import { Transaction } from "sequelize";

interface ISubTask
  extends Omit<
    SubTaskFormikShape,
    | "touched"
    | "index"
    //Generated by GetAllOptionalFields
    //Generated by GetOptionalField - GetOptionalField
    | "finishDateTime"
  > {
  //Generated by GetAllOptionFieldTypes
  finishDateTime?: string | null; //Generated by GetModelFieldType
}

//Reusable functions
export const createSubTask = async (
  subTask: Omit<ISubTask, typeof PRIMARY_KEY>,
  t: Transaction
) => {
  return await SubTask.create(
    {
      //Generated by GetAllFieldsToUpdateBySeqModel
      description: subTask.description!,
      priority: subTask.priority!,
      finishDateTime: subTask.finishDateTime ? subTask.finishDateTime! : null,
      taskID: parseInt(subTask.taskID as string),
    },
    { transaction: t }
  );
};

export const updateSubTask = async (
  subTask: ISubTask,
  primaryKey: keyof ISubTask,
  t: Transaction,
  primaryKeyValue?: string | number
) => {
  await SubTask.update(
    {
      //Generated by GetAllFieldsToUpdateBySeqModel
      description: subTask.description!,
      priority: subTask.priority!,
      finishDateTime: subTask.finishDateTime ? subTask.finishDateTime! : null,
      taskID: parseInt(subTask.taskID as string),
    },
    {
      where: { [primaryKey]: primaryKeyValue || subTask[primaryKey] },
      transaction: t,
      individualHooks: true,
    }
  );
};

export const deleteSubTasks = async (
  primaryKey: keyof Omit<SubTaskFormikShape, "touched">,
  deletedIds: string[] | number[],
  t: Transaction
) => {
  await SubTask.destroy({
    where: { [primaryKey]: { [Op.in]: deletedIds } },
    transaction: t,
  });
};
