//Generated by WriteToUsemodelquery_ts - useModelQuery.ts
import {
  GetTaskCategoriesResponse,
  TaskCategoryDeletePayload,
  TaskCategoryFormUpdatePayload,
  TaskCategoryModel,
  TaskCategorySearchParams,
  TaskCategoryUpdatePayload,
} from "@/interfaces/TaskCategoryInterfaces";
import axiosClient from "@/utils/api";
import {
  DEFAULT_FILTERS,
  MODEL_PATH,
  PRIMARY_KEY,
} from "@/utils/constants/TaskCategoryConstants";
import { getAxiosParams } from "@/utils/utilities";
import {
  QueryMeta,
  UseQueryResult,
  useInfiniteQuery,
  useMutation,
  useQuery,
} from "@tanstack/react-query";

type IndexAndID = {
  index: number;
  id: number | string;
};

type Response = {
  id?: number | string;
  slug?: string;
  //Generated by GetAllRelatedIndexAndID
  Tasks: IndexAndID[];
  TaskTemplates: IndexAndID[];
};

const updateTaskCategory = async (
  payload: TaskCategoryFormUpdatePayload,
  id: string | number
) => {
  const { data } = await axiosClient({
    url: MODEL_PATH + "/" + id,
    method: "put",
    data: payload,
  });

  return data as Response;
};

export const updateTaskCategories = async (
  payload: TaskCategoryUpdatePayload
) => {
  const { data } = (await axiosClient({
    url: `${MODEL_PATH}/multi`,
    method: "post",
    data: payload,
  })) as { data: { recordsCreated: number } };

  return data;
};

export const deleteTaskCategories = async (
  payload: TaskCategoryDeletePayload
) => {
  const { data } = (await axiosClient({
    url: `${MODEL_PATH}`,
    method: "delete",
    data: payload,
  })) as { data: { recordsDeleted: number } };

  return data;
};

const addTaskCategory = async (payload: TaskCategoryFormUpdatePayload) => {
  const { data } = await axiosClient({
    url: MODEL_PATH,
    method: "post",
    data: payload,
  });

  return data as Response;
};

export const getTaskCategory = async ({
  queryKey,
}: {
  queryKey: [string, string];
}) => {
  const { data } = await axiosClient.get<TaskCategoryModel>(
    `${MODEL_PATH}/${queryKey[1]}`
  );
  return data;
};

const addOrUpdateTaskCategory = (payload: TaskCategoryFormUpdatePayload) => {
  if (payload[PRIMARY_KEY]) {
    return updateTaskCategory(payload, payload[PRIMARY_KEY]);
  } else {
    return addTaskCategory(payload);
  }
};

export const useTaskCategoryQuery = (
  slug: string,
  options?: Parameters<typeof useQuery>[2]
) => {
  const taskCategoryMutation = useMutation(addOrUpdateTaskCategory);

  const taskCategoryQuery = useQuery(
    ["taskCategory", slug],
    getTaskCategory,
    //@ts-ignore
    options
  ) as UseQueryResult<TaskCategoryModel, any>;

  return { taskCategoryMutation, taskCategoryQuery };
};

//Generated by GetCodeOriginallyFromModelTable - GetCodeOriginallyFromModelTable
interface GetTaskCategoriesProps {
  pageParam?: string;
  queryKey: [string, Partial<TaskCategorySearchParams>];
  meta: QueryMeta | undefined;
}
const getTaskCategories = async ({
  pageParam = "",
  queryKey,
  meta,
}: GetTaskCategoriesProps) => {
  const [
    _,
    {
      //Generated by GetAllQueryKeyValueOfGetPluralizedModelName
      q = "", //Generated by GetQueryKeyValueOfGetPluralizedModelName - GetQueryKeyValueOfGetPluralizedModelName
      limit = "",
      sort = "",
    },
  ] = queryKey;

  const { fetchCount } = meta!;

  const axiosParams = getAxiosParams(
    {
      //Generated by GetAllFilterQueryNameBySeqModel
      q,
    },
    DEFAULT_FILTERS,
    {
      cursor: pageParam,
      limit,
      sort,
      //@ts-ignore
      fetchCount: fetchCount.toString(),
    }
  ) as Partial<TaskCategorySearchParams>;

  const { data } = await axiosClient.get<GetTaskCategoriesResponse>(
    MODEL_PATH,
    {
      params: axiosParams,
    }
  );

  return data;
};

interface UseTaskCategoriesQueryProps
  extends Partial<TaskCategorySearchParams> {}

export const useTaskCategoriesQuery = ({
  //Generated by GetAllFilterQueryNameBySeqModel
  q,
  limit,
  sort,
  fetchCount,
}: UseTaskCategoriesQueryProps) => {
  const _ = useInfiniteQuery(
    [
      "taskCategories",
      {
        //Generated by GetAllFilterQueryNameBySeqModel
        q,
        limit,
        sort,
      },
    ],
    getTaskCategories,
    {
      keepPreviousData: true,
      getNextPageParam: (lastPage) => lastPage.cursor ?? undefined,
      meta: {
        fetchCount,
      },
    }
  );
  return _;
};
