//Generated by WriteToLucideicons_tsx - LucideIcons.tsx
import {
  Home,
  //Generated by GetAllLucideIcons
  //Generated by GetLucideIcon - GetLucideIcon
  List,
  //Generated by GetLucideIcon - GetLucideIcon
  Clock,
  //Generated by GetLucideIcon - GetLucideIcon
  Tag,
  //Generated by GetLucideIcon - GetLucideIcon
  File,
  //Generated by GetLucideIcon - GetLucideIcon
  CheckSquare,
} from "lucide-react";

export const LucideIcons = {
  Home,
  //Generated by GetAllLucideIconItems
  //Generated by GetLucideIconItem - GetLucideIcon
  List,
  //Generated by GetLucideIconItem - GetLucideIcon
  Clock,
  //Generated by GetLucideIconItem - GetLucideIcon
  Tag,
  //Generated by GetLucideIconItem - GetLucideIcon
  File,
  //Generated by GetLucideIconItem - GetLucideIcon
  CheckSquare,
};
