//Generated by WriteToUsemodelstore_ts - useModelStore.ts
import { Slice, modelSlice } from "@/lib/zustand-slice";
import { TaskIntervalConfig } from "@/utils/config/TaskIntervalConfig";
import { create } from "zustand";

const useTaskIntervalStore = create<Slice<Record<string, unknown>>>((set) =>
  modelSlice(set, TaskIntervalConfig.sortString)
);

export { useTaskIntervalStore };
