//Generated by WriteToModelsPage - Model Page Sidebar
import React from "react";
import TaskIntervalFilterForm from "@/components/task-intervals/TaskIntervalFilterForm";
import TaskIntervalTable from "@/components/task-intervals/TaskIntervalTable";
import PageSession from "@/components/PageSession";
import { TaskIntervalConfig } from "@/utils/config/TaskIntervalConfig";

const config = TaskIntervalConfig;

export const metadata = {
  title: config.pluralizedVerboseModelName,
};

const TaskIntervals: React.FC = () => {
  return (
    <>
      <div className="flex flex-col flex-1 w-full mx-auto text-sm 2xl:px-0 main-height-less-footer">
        <div className="flex flex-col flex-1 w-full gap-4 pl-4 mx-auto rounded-sm">
          <h1 className="text-2xl font-bold">
            {config.pluralizedVerboseModelName}
          </h1>
          <div className="flex">
            <TaskIntervalFilterForm />
          </div>
          <div className="flex flex-col flex-1 ">
            <TaskIntervalTable />
          </div>
        </div>
      </div>
      <PageSession />
    </>
  );
};

export default TaskIntervals;
