//Generated by WriteToUsemodelpageparams_tsx - useModelPageParams.tsx
import { useURL } from "@/hooks/useURL";
import { TaskSearchParams } from "@/interfaces/TaskInterfaces";
import { DEFAULT_LIMIT } from "@/utils/constants";
import { DEFAULT_SORT_BY } from "@/utils/constants/TaskConstants";

export const useTaskPageParams = () => {
  const { query, pathname, router } = useURL<TaskSearchParams>();

  //Generated by GetAllSearchParamsBySeqModel
  const q = query["q"] || "";
  const taskInterval = query["taskInterval"] || ""; //Generated by GetSearchParamVariable - Search Param Variable
  const hasFile = query["hasFile"] || ""; //Generated by GetSearchParamVariable - Search Param Variable
  const status = query["status"]; //Generated by GetSearchParamVariable - Search Param Variable
  const dateFrom = query["dateFrom"] || "";
  const dateTo = query["dateTo"] || ""; //Generated by GetSearchParamVariable - GetDateBetweenSearchParams
  const taskCategory = query["taskCategory"] || ""; //Generated by GetSearchParamVariable - Search Param Variable
  const sort = query["sort"] || DEFAULT_SORT_BY;
  const limit = query["limit"] || DEFAULT_LIMIT;

  return {
    query,
    pathname,
    router,
    params: {
      //Generated by GetAllFilterQueryNameBySeqModel
      q,
      taskInterval, //Generated by GetFilterQueryName
      hasFile, //Generated by GetFilterQueryName
      status, //Generated by GetFilterQueryName
      dateFrom,
      dateTo, //Generated by GetFilterQueryName - GetDateBetweenFilterQueryName
      taskCategory, //Generated by GetFilterQueryName
      sort,
      limit,
    },
  };
};
