//Generated by GetuseModelListts - useModelList.ts
"use client";
import { GetTasksResponse } from "@/interfaces/TaskInterfaces";
import { TaskSearchParams } from "@/interfaces/TaskInterfaces";
import { BasicModel } from "@/interfaces/GeneralInterfaces";
import axiosClient from "@/utils/api";
import { useQuery } from "@tanstack/react-query";
import { useEffect, useState } from "react";

const getTasks = async () => {
  const { data } = await axiosClient.get<GetTasksResponse>(`tasks`, {
    params: {
      fetchCount: "false",
      simpleOnly: "true",
    } as Partial<TaskSearchParams>,
  });

  return data.rows.map((item) => ({
    id: item.id,
    name: item.id.toString(),
  }));
};

interface UseListProps {
  placeholderData?: BasicModel[];
}

const useTaskList = (prop?: UseListProps) => {
  //local states
  const [mounted, setMounted] = useState(false);

  const _ = useQuery({
    queryKey: ["task-list"],
    queryFn: getTasks,
    enabled: mounted,
    placeholderData: prop?.placeholderData,
  });

  useEffect(() => {
    setMounted(true);
  }, []);

  return _;
};

export default useTaskList;
