//Generated by WriteToUsemodelnametable_tsx - useModelNameTable.tsx
import { useTasksQuery } from "@/hooks/tasks/useTaskQuery";
import { useTaskStore } from "@/hooks/tasks/useTaskStore";
import { useURL } from "@/hooks/useURL";
import {
  GetTasksResponse,
  TaskSearchParams,
} from "@/interfaces/TaskInterfaces";
import { DEFAULT_LIMIT } from "@/utils/constants";
import { DEFAULT_SORT_BY } from "@/utils/constants/TagConstants";
import { InfiniteData, useQueryClient } from "@tanstack/react-query";
import { useEffect } from "react";

export const useTaskTable = () => {
  const { query } = useURL<TaskSearchParams>();
  const queryClient = useQueryClient();

  ///Local States

  //SearchParams Variables
  //Generated by GetAllSearchParamsBySeqModel
  const q = query["q"] || "";
  const taskCategory = query["taskCategory"] || "";
  const taskInterval = query["taskInterval"] || "";
  const isFinished = query["isFinished"] || "";
  const sort = query["sort"] || DEFAULT_SORT_BY;
  const limit = query["limit"] || DEFAULT_LIMIT;

  //Page constants

  //Store Variables
  const page = useTaskStore((state) => state.page);
  const recordCount = useTaskStore((state) => state.recordCount);
  const setRecordCount = useTaskStore((state) => state.setRecordCount);
  const lastPage = useTaskStore((state) => state.lastPage);
  const setLastPage = useTaskStore((state) => state.setLastPage);
  const setPage = useTaskStore((state) => state.setPage);
  const fetchCount = useTaskStore((state) => state.fetchCount);
  const setFetchCount = useTaskStore((state) => state.setFetchCount);
  const setCurrentData = useTaskStore((state) => state.setCurrentData);
  const setQueryResponse = useTaskStore((state) => state.setQueryResponse);
  const setRefetchQuery = useTaskStore((state) => state.setRefetchQuery);

  const taskQueryResponse = useTasksQuery({
    //Generated by GetAllFilterQueryNameBySeqModel
    q,
    taskCategory,
    taskInterval,
    isFinished,
    sort,
    limit,
    fetchCount: fetchCount.toString(),
  });

  const { data } = taskQueryResponse;

  //Client functions
  const refetchQuery = (idx: number) => {
    queryClient.setQueryData(
      [
        "tasks",
        {
          //Generated by GetAllFilterQueryNameBySeqModel
          q,
          taskCategory,
          taskInterval,
          isFinished,
          sort,
          limit,
          fetchCount: fetchCount.toString(),
        },
      ],
      (data: InfiniteData<GetTasksResponse> | undefined) => {
        return data
          ? {
              pages: data.pages.slice(0, idx + 1),
              pageParams: data.pageParams.slice(0, idx + 1),
            }
          : undefined;
      }
    );
    taskQueryResponse.refetch();
  };

  useEffect(() => {
    if (data) {
      setQueryResponse(taskQueryResponse);
      const newPage = page === 0 ? 1 : page;
      const newLastPage = lastPage === 0 ? 1 : lastPage;
      setPage(newPage);
      setLastPage(newLastPage);

      const count = data.pages[newPage - 1].count;
      if (count) {
        setRecordCount(count);
      }

      if (fetchCount && count !== recordCount) {
        setFetchCount(false);
      }

      if (data.pages.length >= newPage) {
        setCurrentData(data.pages[newPage - 1].rows);
      }

      !refetchQuery && setRefetchQuery(refetchQuery);
    }
  }, [data]);

  return null;
};
