//Generated by WriteToModeltable_tsx - ModelTable.tsx
"use client";
import React, { useEffect } from "react";
import { useTaskIntervalStore } from "@/hooks/task-intervals/useTaskIntervalStore";
import {
  TaskIntervalModel,
  TaskIntervalSearchParams,
} from "@/interfaces/TaskIntervalInterfaces";
import { useQueryClient } from "@tanstack/react-query";
import { Formik } from "formik";
import { TaskIntervalConfig } from "@/utils/config/TaskIntervalConfig";
import { useModelPageParams } from "@/hooks/useModelPageParams";
import { getInitialValues } from "@/lib/getInitialValues";
import { BasicModel, GetModelsResponse } from "@/interfaces/GeneralInterfaces";
import { createRequiredModelLists } from "@/lib/createRequiredModelLists";
import { useModelsQuery, useUpdateModelsMutation } from "@/hooks/useModelQuery";
import { ModelSchema } from "@/schema/ModelSchema";
import ModelFormArray from "@/components/ModelFormArray";
import { getCurrentData } from "@/lib/getCurrentData";
import { getRefetchQueryFunction } from "@/lib/refetchQuery";
import { toast } from "@/hooks/use-toast";

const TaskIntervalTable: React.FC = () => {
  const modelConfig = TaskIntervalConfig;
  const { pluralizedModelName } = modelConfig;
  const { params } = useModelPageParams<TaskIntervalSearchParams>(modelConfig);
  const queryClient = useQueryClient();

  const [mounted, setMounted] = React.useState(false);

  const requiredList: Record<string, BasicModel[]> =
    createRequiredModelLists(modelConfig);

  //Page constants
  const defaultFormValue = getInitialValues(modelConfig, undefined, {
    childMode: true,
    requiredList,
  });

  //Store Variables
  const page = useTaskIntervalStore((state) => state.page);
  const setRecordCount = useTaskIntervalStore((state) => state.setRecordCount);
  const fetchCount = useTaskIntervalStore((state) => state.fetchCount);
  const setFetchCount = useTaskIntervalStore((state) => state.setFetchCount);
  const previousData = useTaskIntervalStore((state) => state.currentData);
  const setCurrentData = useTaskIntervalStore((state) => state.setCurrentData);
  const setQueryResponse = useTaskIntervalStore(
    (state) => state.setQueryResponse
  );
  const setRefetchQuery = useTaskIntervalStore(
    (state) => state.setRefetchQuery
  );

  const recordCount = useTaskIntervalStore((state) => state.recordCount);
  const setIsUpdating = useTaskIntervalStore((state) => state.setIsUpdating);
  const isUpdating = useTaskIntervalStore((state) => state.isUpdating);
  const setPage = useTaskIntervalStore((state) => state.setPage);
  const lastFetchedPage = useTaskIntervalStore(
    (state) => state.lastFetchedPage
  );

  const queryParams = params;
  const useTaskIntervalSearchQuery = () =>
    useModelsQuery<TaskIntervalModel>(modelConfig, {
      ...params,
      fetchCount: fetchCount.toString(),
    });

  const queryResponse = useTaskIntervalSearchQuery();
  const { data, refetch, isFetching } = queryResponse;

  const currentPageData: GetModelsResponse<TaskIntervalModel> | null = data
    ? data.pages[page - (isFetching ? 2 : 1)]
    : null;
  const currentData: any[] = getCurrentData(
    currentPageData,
    previousData as any,
    defaultFormValue
  );

  //Client functions
  const refetchQuery = getRefetchQueryFunction(
    modelConfig,
    params,
    refetch,
    queryClient
  );

  const updateModelsMutation = useUpdateModelsMutation(modelConfig);

  //Client Actions
  const handleSubmit = async (values: any) => {
    //The reference is the index of the row
    //@ts-ignore
    const rowsToBeSubmitted = values[pluralizedModelName].filter(
      //@ts-ignore
      (item) => item.touched
    );

    if (rowsToBeSubmitted.length > 0) {
      setIsUpdating(true);
      const payload = {
        [pluralizedModelName]: rowsToBeSubmitted,
      };

      //@ts-ignore
      updateModelsMutation.mutateAsync(payload).then((data) => {
        console.log(data);
        setIsUpdating(false);
        toast({
          variant: "success",
          description: `${modelConfig.pluralizedVerboseModelName} successfully updated`,
        });
      });
    }
  };

  useEffect(() => {
    if (currentPageData?.count !== undefined) {
      setRecordCount(currentPageData?.count || 0);
    }
    setFetchCount(!fetchCount);
    setCurrentData(currentData);
    setRefetchQuery(refetchQuery);
  }, [currentPageData?.count, data, page]);

  useEffect(() => {
    setMounted(true);
  }, []);

  return (
    mounted && (
      <Formik
        initialValues={{
          [pluralizedModelName]: currentData,
        }}
        enableReinitialize={true}
        onSubmit={handleSubmit}
        validationSchema={ModelSchema(modelConfig, true)}
        validateOnChange={false}
      >
        {(formik) => (
          <ModelFormArray
            formik={formik as any}
            modelConfig={modelConfig}
            storeStates={{
              currentData,
              page,
              recordCount,
              isUpdating,
              setPage,
              lastFetchedPage,
              setRecordCount,
            }}
            queryResponse={queryResponse as any}
            refetchQuery={refetchQuery}
          />
        )}
      </Formik>
    )
  );
};

export default TaskIntervalTable;
