//Generated by WriteToModelformarray_tsx - ModelFormArray.tsx
import { TaskIntervalColumns } from "@/components/task-intervals/TaskIntervalColumns";
import { TaskIntervalMultiCreateDeleteDialog } from "@/components/task-intervals/TaskIntervalMultiCreateDeleteDialog";
import { Button } from "@/components/ui/Button";
import { DataTable } from "@/components/ui/DataTable";
import { useTaskIntervalDeleteDialog } from "@/hooks/task-intervals/useTaskIntervalDeleteDialog";
import { useTaskIntervalPageParams } from "@/hooks/task-intervals/useTaskIntervalPageParams";
import { useTaskIntervalStore } from "@/hooks/task-intervals/useTaskIntervalStore";
import { TaskIntervalFormikShape } from "@/interfaces/TaskIntervalInterfaces";
import {
  DEFAULT_FORM_VALUE,
  FIRST_FIELD_IN_FORM,
  LAST_FIELD_IN_FORM,
  PLURALIZED_MODEL_NAME,
} from "@/utils/constants/TaskIntervalConstants";
import { getSorting } from "@/utils/utilities";
import { encodeParams, removeItemsByIndexes } from "@/utils/utils";
import {
  useReactTable,
  getCoreRowModel,
  SortingState,
} from "@tanstack/react-table";
import { Form, FormikProps } from "formik";
import { ChevronLast, Plus, Trash } from "lucide-react";
import React, { useEffect, useRef, useState } from "react";

interface TaskIntervalFormArrayProps {
  formik: FormikProps<{ TaskIntervals: TaskIntervalFormikShape[] }>;
}

const TaskIntervalFormArray: React.FC<TaskIntervalFormArrayProps> = ({
  formik,
}) => {
  const { query, router, pathname, params } = useTaskIntervalPageParams();
  const { sort, limit } = params;

  //Local states
  const [willFocus, setWillFocus] = useState(false);
  const ref: React.RefObject<HTMLElement> = useRef(null); //to be attached to the last row in form, first control in that row

  const currentData = useTaskIntervalStore((state) => state.currentData);
  const queryResponse = useTaskIntervalStore((state) => state.queryResponse);
  const resetRowSelection = useTaskIntervalStore(
    (state) => state.resetRowSelection
  );
  const rowSelection = useTaskIntervalStore((state) => state.rowSelection);
  const setRowSelection = useTaskIntervalStore(
    (state) => state.setRowSelection
  );
  const setRowSelectionToAll = useTaskIntervalStore(
    (state) => state.setRowSelectionToAll
  );
  const page = useTaskIntervalStore((state) => state.page);
  const recordCount = useTaskIntervalStore((state) => state.recordCount);
  const isUpdating = useTaskIntervalStore((state) => state.isUpdating);
  const setPage = useTaskIntervalStore((state) => state.setPage);
  const lastFetchedPage = useTaskIntervalStore(
    (state) => state.lastFetchedPage
  );

  const setRecordsToDelete = useTaskIntervalDeleteDialog(
    (state) => state.setRecordsToDelete
  );

  //Page Constants
  const DEFAULT_TASKINTERVAL = DEFAULT_FORM_VALUE;

  //Tanstacks
  const {
    data: taskIntervalData,
    isLoading,
    isFetching,
    fetchNextPage,
  } = queryResponse!();

  //Transformations
  const sorting = getSorting(sort);
  const hasSelected = Object.values(rowSelection).some((val) => val);
  const dataRowCount = taskIntervalData
    ? currentData.length + (page - 1) * parseInt(limit)
    : 0;
  const pageStatus = `Showing ${dataRowCount} of ${recordCount} record(s)`;
  const hasPreviousPage = page > 1;
  const hasNextPage = dataRowCount < recordCount;

  //Client Actions
  const focusOnRef = () => {
    ref && ref.current?.focus();
  };

  const addRow = () => {
    formik.setFieldValue(`TaskIntervals`, [
      ...formik.values.TaskIntervals.map((item) => ({ ...item })),
      { ...DEFAULT_TASKINTERVAL },
    ]);
    setWillFocus(true);
  };

  const setTouchedRows = (idx: number) => {
    formik.setFieldValue(`TaskIntervals[${idx}].touched`, true);
  };

  const deleteRow = (idx: number) => {
    const id = formik.values.TaskIntervals[idx].id;

    if (id) {
      setRecordsToDelete([id.toString()]);
    } else {
      formik.setFieldValue(`TaskIntervals`, [
        ...formik.values.TaskIntervals.slice(0, idx),
        ...formik.values.TaskIntervals.slice(idx + 1),
      ]);
      formik.setErrors({});
      resetRowSelection();
    }
  };

  const deleteSelectedRows = () => {
    const indexes = Object.keys(rowSelection).map((item) => parseInt(item));

    //Compute the Ids to be deleted. the index should be the selected indexes. then see if the rows has an actual id value
    const deletedIDs = formik.values.TaskIntervals.filter((_, idx) =>
      indexes.includes(idx)
    )
      .filter((item) => !!item.id)
      .map((item) => item.id.toString());

    if (deletedIDs.length > 0) {
      setRecordsToDelete(deletedIDs);
    } else {
      formik.setFieldValue(
        `TaskIntervals`,
        removeItemsByIndexes(formik.values.TaskIntervals, indexes)
      );
      formik.setErrors({});
      resetRowSelection();
    }
  };

  const toggleRow = (idx: number) => setRowSelection(idx);
  const toggleSelectAllRow = () => {
    if (
      Object.keys(rowSelection).length === formik.values.TaskIntervals.length
    ) {
      resetRowSelection();
    } else {
      setRowSelectionToAll(formik.values.TaskIntervals.length);
    }
  };

  const goToPreviousPage = () => {
    if (taskIntervalData) {
      const newPage = page - 1;
      setPage(newPage);
      resetRowSelection();
    }
  };

  const goToNextPage = () => {
    if (taskIntervalData) {
      const newPage = page + 1;
      if (newPage <= lastFetchedPage) {
        setPage(newPage);
      } else {
        setPage(newPage);
        fetchNextPage();
      }
      resetRowSelection();
    }
  };

  const handleSortChange = (sortingState: SortingState) => {
    const sortParams = sortingState
      .map((item) => {
        if (item.desc) {
          return `-${item.id}`;
        } else {
          return `${item.id}`;
        }
      })
      .join(",");

    const params = { ...query, sort: sortParams };
    const newURL = `${pathname}?${encodeParams(params)}`;
    router.push(newURL);

    resetRowSelection();
  };

  const taskIntervalTable = useReactTable<TaskIntervalFormikShape>({
    data: formik.values.TaskIntervals,
    columns: TaskIntervalColumns,
    state: {
      sorting: sorting,
      rowSelection,
    },
    //@ts-ignore
    onRowSelectionChange: (state) => setRowSelection(state()),
    //@ts-ignore
    onSortingChange: (state) => handleSortChange(state()), //since the sort state is getting tracked from the url do handle instead
    getCoreRowModel: getCoreRowModel(),
    manualFiltering: true,
    manualSorting: true,
    enableMultiRowSelection: true,
    meta: {
      name: PLURALIZED_MODEL_NAME,
      setTouchedRows,
      addRow,
      deleteRow,
      toggleRow,
      toggleSelectAllRow,
      firstFieldInForm: FIRST_FIELD_IN_FORM,
      lastFieldInForm: LAST_FIELD_IN_FORM,
      forwardedRef: ref,
      editable: true,
      options: {},
    },
  });

  //useEffects here
  useEffect(() => {
    if (willFocus) {
      focusOnRef();
    }
  }, [formik.values.TaskIntervals]);

  return (
    <Form
      className="flex flex-col flex-1 gap-4"
      autoComplete="off"
      noValidate
    >
      <div className="flex items-center gap-4">
        <div className="text-sm">
          {taskIntervalTable.getFilteredSelectedRowModel().rows.length} of{" "}
          {taskIntervalTable.getFilteredRowModel().rows.length} row(s) selected.
        </div>
        {hasSelected && (
          <Button
            type="button"
            size={"sm"}
            variant={"destructive"}
            onClick={() => {
              deleteSelectedRows();
            }}
            className="flex items-center justify-center gap-2"
          >
            Delete Selected
            <Trash className="w-4 h-4 text-foreground" />
          </Button>
        )}
        <Button
          className="ml-auto"
          variant={"secondary"}
          type="button"
          size="sm"
          onClick={focusOnRef}
        >
          <ChevronLast className="w-4 h-4 text-foreground" /> Go to last row
        </Button>
      </div>

      <div className="border rounded-md">
        <DataTable
          isLoading={isLoading}
          table={taskIntervalTable}
        />
      </div>
      <div className="flex items-center justify-between mt-auto text-sm select-none text-muted-foreground">
        {!isLoading && (
          <div className="flex items-center justify-between w-full gap-4">
            <p className="hidden md:block">{pageStatus}</p>
            <div className="flex gap-2">
              <Button
                type="button"
                size="sm"
                variant={"secondary"}
                onClick={addRow}
                isLoading={isUpdating}
              >
                <Plus className="w-4 h-4 mr-1 text-foreground" />
                Add Row
              </Button>
              <Button
                type="submit"
                size={"sm"}
                isLoading={isUpdating}
                variant={"secondary"}
              >
                Save Changes
              </Button>
              <Button
                type="button"
                size="sm"
                disabled={!hasPreviousPage}
                onClick={() => goToPreviousPage()}
                variant={"secondary"}
              >
                Previous
              </Button>
              <Button
                type="button"
                size="sm"
                disabled={!hasNextPage}
                onClick={() => goToNextPage()}
                isLoading={isFetching}
                variant={"secondary"}
              >
                Next
              </Button>
            </div>
          </div>
        )}
      </div>
      <TaskIntervalMultiCreateDeleteDialog />
    </Form>
  );
};

export default TaskIntervalFormArray;
