//Generated by ImportCompleteModelFile
//Generated by GetCompleteModelFile

//Generated by GetModelImports
import {CreationOptional,DataTypes,InferAttributes,InferCreationAttributes,Model,Sequelize} from "sequelize";
import sequelize from "../config/db";

//Generated by GetModelInterface
export default interface TaskInterval extends Model<InferAttributes<TaskInterval>, InferCreationAttributes<TaskInterval>>
{id: CreationOptional<number>;
name: string}

//Generated by GetModelDefinition
export const TaskInterval = sequelize.define<TaskInterval>(
"TaskInterval",
//Generated by GetModelFieldsDictionary
{
 id: {
  type: DataTypes.BIGINT,
  autoIncrement: true,
  primaryKey: true,
  field: "id"
 }
 ,
 name: {
  type: DataTypes.STRING(50),
  unique: true,
  field: "name"
 }
}
,
//Generated By GetModelOptionDict
{
  name: {singular: "TaskInterval",plural:"TaskIntervals"},
  tableName: "taskmanager_taskinterval",
  timestamps: false
}
);

//Generated by GenerateSyncModel
export const TaskIntervalSync = async () => {
  try {
    await TaskInterval.sync({ alter: true });
    console.log("Task Interval table has been created!");
  } catch (error) {
    console.error(
      `Unable to create ${"Task Interval".toLowerCase()} table:`,
      error
    );
  }
};
