//Generated by WriteToMultiRoute_ts - multi route.ts
import sequelize from "@/config/db";
import {
  createTaskCategory,
  updateTaskCategory,
} from "@/utils/api/TaskCategoryLibs";
import { TaskCategoryUpdatePayload } from "@/interfaces/TaskCategoryInterfaces";
import { TaskCategorySchema } from "@/schema/TaskCategorySchema";
import {
  PRIMARY_KEY,
  UNIQUE_FIELDS,
} from "@/utils/constants/TaskCategoryConstants";
import handleSequelizeError from "@/utils/errorHandling";
import { checkDuplicateCombinations, returnJSONResponse } from "@/utils/utils";
import { NextResponse } from "next/server";

//Generated by GetMultiCreateModelPOSTRoute - GetMultiCreateModelPOSTRoute
export const POST = async (req: Request) => {
  const body = (await req.json()) as TaskCategoryUpdatePayload;
  const { TaskCategories } = body;

  //Generated by GenerateUniquenessValidation
  //Validate record uniqueness

  UNIQUE_FIELDS.forEach((item) => {
    const uniquenessError = checkDuplicateCombinations(item, TaskCategories);

    if (uniquenessError) {
      return returnJSONResponse({
        status: "error",
        error: uniquenessError,
        errorCode: 422,
      });
    }
  });

  const t = await sequelize.transaction();
  let recordsCreated = 0;

  for (const item of TaskCategories) {
    try {
      await TaskCategorySchema.validate(item);
    } catch (error) {
      return handleSequelizeError(error);
    }
  }

  try {
    for (const item of TaskCategories) {
      if (item[PRIMARY_KEY] === "") {
        await createTaskCategory(item, t);
        recordsCreated++;
      } else {
        await updateTaskCategory(item, PRIMARY_KEY, t);
      }
    }

    await t.commit();

    return NextResponse.json({
      recordsCreated,
    });
  } catch (err) {
    await t.rollback();
    return handleSequelizeError(err);
  }
};
