//Generated by WriteToModelschema_ts - ModelSchema.ts
import * as Yup from "yup";

const TagSchema = Yup.object().shape({
  //Generated by GetAllFieldValidationBySeqModel
name: Yup.string().nullable().transform((value, originalValue) =>originalValue && originalValue !== "" ? value : null),
  
});

const TagArraySchema = Yup.object().shape({
  Tags: Yup.array().of(
    Yup.object().shape({
     //Generated by GetAllArrayFieldValidationBySeqModel
name: Yup.string().nullable()
    })
  ),
});

export { TagSchema, TagArraySchema };
