//Generated by WriteToModelschema_ts - ModelSchema.ts
import * as Yup from "yup";

const TaskNoteSchema = Yup.object().shape({
  //Generated by GetAllFieldValidationBySeqModel
  note: Yup.string().required("Note is a required field."),
  taskID: Yup.number().required("Task ID is a required field."),
  file: Yup.string().required("File is a required field."),
});

const TaskNoteArraySchema = Yup.object().shape({
  TaskNotes: Yup.array().of(
    Yup.object().shape({
      //Generated by GetAllArrayFieldValidationBySeqModel
      note: Yup.string().when("touched", ([touched], schema) =>
        touched
          ? schema.required("Note is a required field.")
          : schema.notRequired()
      ),
      taskID: Yup.number().when("touched", ([touched], schema) =>
        touched
          ? schema.required("Task ID is a required field.")
          : schema.notRequired()
      ),
      file: Yup.string().when("touched", ([touched], schema) =>
        touched
          ? schema.required("File is a required field.")
          : schema.notRequired()
      ),
    })
  ),
});

export { TaskNoteSchema, TaskNoteArraySchema };
