//Generated by WriteToModelschema_ts - ModelSchema.ts
import * as Yup from "yup";

const TaskNoteSchema = Yup.object().shape({
  //Generated by GetAllFieldValidationBySeqModel
  note: Yup.string()
    .nullable()
    .transform((value, originalValue) =>
      originalValue && originalValue !== "" ? value : null
    ),
  taskID: Yup.number().required("Task ID is a required field."),
  file: Yup.string()
    .nullable()
    .transform((value, originalValue) =>
      originalValue && originalValue !== "" ? value : null
    ),
  fileSize: Yup.number()
    .nullable()
    .transform((value, originalValue) =>
      originalValue && originalValue !== "" ? value : null
    ),
  fileName: Yup.string()
    .nullable()
    .transform((value, originalValue) =>
      originalValue && originalValue !== "" ? value : null
    ),
});

const TaskNoteArraySchema = Yup.object().shape({
  TaskNotes: Yup.array().of(
    Yup.object().shape({
      //Generated by GetAllArrayFieldValidationBySeqModel
      note: Yup.string().nullable(),
      taskID: Yup.number().when("touched", ([touched], schema) =>
        touched
          ? schema.required("Task ID is a required field.")
          : schema.notRequired()
      ),
      file: Yup.string().nullable(),
      fileSize: Yup.number().nullable(),
      fileName: Yup.string().nullable(),
    })
  ),
});

export { TaskNoteSchema, TaskNoteArraySchema };
